package com.anydownlod.desktop

import androidx.compose.runtime.remember
import androidx.compose.ui.unit.DpSize
import androidx.compose.ui.unit.dp
import androidx.compose.ui.window.Window
import androidx.compose.ui.window.application
import androidx.compose.ui.window.rememberWindowState
import com.anydownlod.core.AppGraph
import com.anydownlod.desktop.engine.CliProcessRunner
import com.anydownlod.desktop.engine.ExecutableOnPath
import com.anydownlod.desktop.engine.JavaCliProcessRunner
import com.anydownlod.desktop.store.DesktopStore
import com.anydownlod.desktop.store.defaultDownloadRootPath
import com.anydownlod.desktop.store.defaultStateDirectory
import com.anydownlod.ui.App
import dev.zacsweers.metro.createGraphFactory
import java.nio.file.Path
import kotlinx.coroutines.CoroutineDispatcher
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.cancel

fun main() = application {
    val desktop = remember { DesktopApp.open() }
    Window(
        onCloseRequest = {
            desktop.close()
            exitApplication()
        },
        title = "AnyDownload",
        state = rememberWindowState(size = DpSize(1280.dp, 860.dp)),
    ) {
        App(desktop.graph)
    }
}

/**
 * The desktop host: JSON store, yt-dlp engine, and the graph the shared
 * screens consume. `apps/desktop` is the only module that starts processes.
 *
 * T-116: the graph is generated by Metro. [open] keeps the five runtime
 * inputs and hands them to [DesktopGraph.Factory]; it still loads
 * [DesktopStore], persists the normalized rows once at startup, saves all
 * state on close, and shuts the CLI engine down through the graph.
 */
internal class DesktopApp(
    val store: DesktopStore,
    val graph: AppGraph,
    private val shutdownEngine: () -> Unit,
) {
    /** Destroys any live process, then persists the final state. */
    fun close() {
        shutdownEngine()
        store.saveAll(
            jobs = graph.engine.jobs.value,
            subscriptions = graph.subscriptions.subscriptions.value,
            settings = graph.settings.settings.value,
        )
    }

    companion object {
        fun open(
            stateDirectory: Path = defaultStateDirectory(),
            defaultDownloadRoot: () -> String = { defaultDownloadRootPath() },
            processRunner: CliProcessRunner = JavaCliProcessRunner,
            resolveExecutable: (String) -> String? = ExecutableOnPath::find,
            ioDispatcher: CoroutineDispatcher = Dispatchers.IO,
        ): DesktopApp {
            val graph = createGraphFactory<DesktopGraph.Factory>().create(
                stateDirectory = stateDirectory,
                defaultDownloadRoot = DesktopDefaultDownloadRoot(defaultDownloadRoot),
                processRunner = processRunner,
                resolveExecutable = resolveExecutable,
                ioDispatcher = ioDispatcher,
            )
            // Persist the normalized rows (interrupted jobs, default root).
            graph.store.saveAll(
                jobs = graph.engine.jobs.value,
                subscriptions = graph.subscriptions.subscriptions.value,
                settings = graph.settings.settings.value,
            )
            return DesktopApp(
                store = graph.store,
                graph = graph,
                shutdownEngine = {
                    graph.cliEngine.shutdown()
                    graph.scope.cancel()
                },
            )
        }
    }
}
