package com.anydownlod.core.format

import com.anydownlod.core.extract.MediaFormat

/** Synthetic formats for the selector/sorter tests; no live hosts. */
internal fun format(
    id: String? = null,
    url: String? = "https://fixtures.example.net/media.bin",
    ext: String? = null,
    protocol: String? = null,
    vcodec: String? = null,
    acodec: String? = null,
    width: Long? = null,
    height: Long? = null,
    fps: Double? = null,
    tbr: Double? = null,
    abr: Double? = null,
    vbr: Double? = null,
    asr: Long? = null,
    filesize: Long? = null,
    filesizeApprox: Long? = null,
    audioChannels: Long? = null,
    dynamicRange: String? = null,
    languagePreference: Double? = null,
    language: String? = null,
    quality: String? = null,
    preference: Int? = null,
    sourcePreference: Int? = null,
    hasDrm: Boolean? = null,
): MediaFormat = MediaFormat(
    formatId = id,
    url = url,
    ext = ext,
    protocol = protocol,
    vcodec = vcodec,
    acodec = acodec,
    width = width,
    height = height,
    fps = fps,
    tbr = tbr,
    abr = abr,
    vbr = vbr,
    asr = asr,
    filesize = filesize,
    filesizeApprox = filesizeApprox,
    audioChannels = audioChannels,
    dynamicRange = dynamicRange,
    languagePreference = languagePreference,
    language = language,
    quality = quality,
    preference = preference,
    sourcePreference = sourcePreference,
    hasDrm = hasDrm,
)
