/*
 * Coverage block generation — AnyDownload repository tooling (T-055).
 *
 * Renders the block between the markers in
 * vault/01-product/Ytdlp-equivalence.md and replaces it in place. Counts are
 * never rounded up: Not started is the upstream catalog size minus the named
 * extractor modules.
 */
package com.anydownlod.portmanifest

data class CoverageCounts(
    val ported: Int,
    val partial: Int,
    val planned: Int,
    val notStarted: Int,
    val total: Int,
)

object Coverage {
    const val START_MARKER = "<!-- port-manifest:coverage:start -->"
    const val END_MARKER = "<!-- port-manifest:coverage:end -->"

    fun counts(manifest: PortManifest, upstreamCount: Int): CoverageCounts {
        require(upstreamCount >= 0) { "upstreamCount must not be negative" }
        val extractors = manifest.modules.filter { it.kind == ManifestSchema.EXTRACTOR_KIND }
        val ported = extractors.count { it.status == "ported" }
        val partial = extractors.count { it.status == "partial" }
        val planned = extractors.count { it.status == "planned" }
        val named = ported + partial + planned
        require(named <= upstreamCount) {
            "manifest names $named extractors but the upstream list has $upstreamCount"
        }
        return CoverageCounts(
            ported = ported,
            partial = partial,
            planned = planned,
            notStarted = upstreamCount - named,
            total = upstreamCount,
        )
    }

    fun render(manifest: PortManifest, upstream: UpstreamExtractors): String {
        val counts = counts(manifest, upstream.extractors.size)
        val visible = manifest.modules.filter { it.status != "not-started" }
        return buildString {
            appendLine(
                "_Generated by `./gradlew :tools:port-manifest:run` from `port/manifest.json`; " +
                    "validated by `./gradlew :tools:port-manifest:check`. Do not edit this block by hand._",
            )
            appendLine()
            appendLine(
                "Upstream `yt-dlp/yt-dlp` tag `${upstream.tag}`, commit `${upstream.commit}` " +
                    "(Unlicense). The catalog names **${formatCount(counts.total)}** extractor classes.",
            )
            appendLine()
            appendLine("| Extractor catalog | Count |")
            appendLine("| --- | ---: |")
            appendLine("| Ported | ${formatCount(counts.ported)} |")
            appendLine("| Partial | ${formatCount(counts.partial)} |")
            appendLine("| Planned | ${formatCount(counts.planned)} |")
            appendLine("| Not started | ${formatCount(counts.notStarted)} |")
            appendLine("| **Total upstream classes** | **${formatCount(counts.total)}** |")
            if (visible.isEmpty()) {
                appendLine()
                append("No module has been ported, partially ported, or planned yet.")
            } else {
                appendLine()
                appendLine(
                    "| Module | Kind | Upstream path | Status | Scope | Kotlin files | Tasks | Ported |",
                )
                appendLine("| --- | --- | --- | --- | --- | --- | --- | --- |")
                for (module in visible) {
                    appendLine(
                        "| `" + cell(module.id) + "` | " + cell(module.kind) + " | `" + cell(module.upstreamPath) +
                            "` | " + cell(module.status) + " | " + cell(module.scope) + " | " +
                            kotlinFilesCell(module.kotlinFiles) + " | " +
                            cell(module.tasks.joinToString(", "), empty = "—") + " | " +
                            cell(module.portedAt ?: "—") + " |",
                    )
                }
            }
        }.trimEnd('\n').plus("\n")
    }

    /** Content between the markers, without the markers themselves. */
    fun block(note: String): String {
        val startCount = Regex(Regex.escape(START_MARKER)).findAll(note).count()
        val endCount = Regex(Regex.escape(END_MARKER)).findAll(note).count()
        require(startCount == 1 && endCount == 1) {
            "expected exactly one pair of port-manifest coverage markers in the equivalence note " +
                "(found $startCount start, $endCount end)"
        }
        val start = note.indexOf(START_MARKER) + START_MARKER.length
        val end = note.indexOf(END_MARKER)
        require(start <= end) { "port-manifest coverage markers are out of order" }
        return note.substring(start, end)
    }

    fun replaceBlock(note: String, blockContent: String): String {
        block(note) // validates the markers before rewriting
        val start = note.indexOf(START_MARKER) + START_MARKER.length
        val end = note.indexOf(END_MARKER)
        val replacement = "\n" + blockContent.trim('\n') + "\n"
        return note.substring(0, start) + replacement + note.substring(end)
    }

    private fun kotlinFilesCell(files: List<String>): String {
        if (files.isEmpty()) return "—"
        return files.joinToString("<br>") { file ->
            "[" + "`" + file.substringAfterLast('/') + "`](../../$file)"
        }
    }

    private fun cell(text: String, empty: String = "—"): String {
        val collapsed = text.replace("\n", " ").replace("|", "\\|").trim()
        return collapsed.ifEmpty { empty }
    }

    /** Group digits with commas without depending on the host locale. */
    fun formatCount(value: Int): String {
        require(value >= 0) { "count must not be negative" }
        val digits = value.toString()
        if (digits.length <= 3) return digits
        return digits.reversed().chunked(3).joinToString(",").reversed()
    }
}

/** Fixed by the pin and by the task note; stored in the manifest data file. */
const val UPSTREAM_SOURCE_PATH: String = "yt_dlp/extractor/_extractors.py"
